[package]
name = "knots"
version = "0.1.0"
authors = ["mwalczyk <mwalczyk2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.6.5"
glutin = "0.10.1"
cgmath = "0.15.0"
csv = "1.1.1"